//Signup
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//clear success/error messages
export const CLEAR_AUTH_MESSAGES = 'CLEAR_AUTH_MESSAGES';

//persist logged in users
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

//forgetPassword
export const FORGET_PASSWORD_START = 'FORGET_PASSWORD_START';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

//logout
export const USER_LOGOUT = 'USER_LOGOUT';

//resetPassword
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//locate dealerships
export const LOCATE_DEALERSHIP_SUCCESS = 'LOCATE_DEALERSHIP_SUCCESS';
export const LOCATE_DEALERSHIP_FAILURE = 'LOCATE_DEALERSHIP_FAILURE';

//testride booking
export const TESTRIDE_BOOKING_START = 'TESTRIDE_BOOKING_START';
export const TESTRIDE_BOOKING_SUCCESS = 'TESTRIDE_BOOKING_SUCCESS';
export const TESTRIDE_BOOKING_FAILURE = 'TESTRIDE_BOOKING_FAILURE';

//clear testride booking messages
export const CLEAR_TESTRIDE_BOOKING_MESSAGE = 'CLEAR_TESTRIDE_BOOKING_MESSAGE';
